/** Textes de la page /affiliation (programme partenaires), FR et EN. */
export const copy = {
  fr: {
    eyebrow: "Programme partenaires",
    titleLead: "Recommandez Granit.",
    titleAccent: "Soyez rémunéré à chaque client signé.",
    intro:
      "Vous accompagnez des professionnels de santé : cabinets dentaires, opticiens, audioprothésistes, pharmacies, cliniques, EHPAD, laboratoires. Présentez-leur Granit, on s'occupe de la démo et du démarrage, vous touchez une commission.",
    cta: "Devenir partenaire",
    flow: [
      { k: "Vous", v: "présentez Granit à un professionnel de santé" },
      { k: "Granit", v: "fait la démo et le suivi" },
      { k: "L'établissement", v: "démarre, sans rien installer" },
      { k: "Vous", v: "êtes rémunéré" },
    ],
    whyEyebrow: "Les avantages",
    whyTitle: "Un programme simple,",
    whyAccent: "pensé pour le terrain.",
    why: [
      {
        title: "Un sujet que vos clients vivent tous les jours",
        text: "Tiers payant, rejets, facturation, relances, dossiers administratifs : la paperasse pèse sur chaque établissement de santé. Les agents Granit s'en chargent, branchés sur les outils existants.",
      },
      {
        title: "Une commission sur chaque client signé",
        text: "Prime par établissement ou pourcentage récurrent : on choisit ensemble la formule qui colle à votre activité, et elle est écrite noir sur blanc avant la première recommandation.",
      },
      {
        title: "Vous recommandez, on fait le reste",
        text: "Pas besoin de vendre. Vous recevez un kit de présentation et un contact dédié chez Granit, qui gère la démo, le démarrage et vous tient au courant.",
      },
    ],
    sectorsEyebrow: "Là où nos agents tournent",
    sectors: ["Dentaire", "Optique", "Audio", "Clinique", "EHPAD", "Pharmacie", "Labo pharma", "Labo bio", "Orthodontie"],
    sectorsLink: "Voir les agents",
    whoEyebrow: "Pour qui",
    who: [
      "Gestionnaires tiers payant et facturation",
      "Consultants et formateurs santé",
      "Experts-comptables",
      "Groupements, réseaux et fédérations",
      "Éditeurs et fournisseurs du secteur",
      "Créateurs de contenu santé",
    ],
    stepsEyebrow: "Comment ça marche",
    stepsTitle: "Trois étapes,",
    stepsAccent: "pas de paperasse.",
    steps: [
      { n: "01", title: "Vous candidatez", text: "Deux minutes, via le formulaire ci-dessous." },
      {
        n: "02",
        title: "On s'appelle",
        text: "Vingt minutes pour se connaître, fixer votre rémunération et vous envoyer le kit partenaire.",
      },
      {
        n: "03",
        title: "Vous recommandez",
        text: "Vous nous présentez un établissement, on s'occupe de tout, et vous êtes rémunéré quand il démarre.",
      },
    ],
    formEyebrow: "Candidature",
    formTitle: "Rejoindre le programme",
    formIntro: "On revient vers vous sous 48 h pour caler un premier appel.",
    fields: {
      name: "Prénom et nom",
      email: "E-mail",
      phone: "Téléphone",
      company: "Structure",
      profile: "Votre activité",
      message: "Comment pensez-vous recommander Granit ? (facultatif)",
    },
    placeholders: {
      name: "Marie Dupont",
      email: "marie@cabinet-conseil.fr",
      phone: "06 12 34 56 78",
      company: "Cabinet, société, réseau…",
      message: "Secteurs et nombre de clients accompagnés, newsletter, formation…",
    },
    choose: "Choisir…",
    profiles: [
      "Gestionnaire tiers payant / facturation",
      "Consultant / formateur",
      "Expert-comptable",
      "Groupement / réseau / fédération",
      "Éditeur / fournisseur",
      "Créateur de contenu",
      "Autre",
    ],
    submit: "Envoyer ma candidature",
    sending: "Envoi…",
    note: "Gratuit et sans engagement. Vos données restent chez nous.",
    success: "Candidature reçue, merci.",
    successSub: "On revient vers vous sous 48 h pour caler un premier appel.",
    error: "Une erreur est survenue. Réessayez, ou écrivez-nous à contact@getgranit.ai.",
    faqTitle: "Questions fréquentes",
    faq: [
      {
        q: "Faut-il être client Granit pour devenir partenaire ?",
        a: "Non. Le programme s'adresse à celles et ceux qui accompagnent des professionnels de santé, quel que soit leur métier.",
      },
      {
        q: "Combien vais-je toucher ?",
        a: "Ça dépend de votre activité : une prime fixe par établissement signé, ou un pourcentage récurrent. On le fixe ensemble au premier appel, par écrit.",
      },
      {
        q: "Dois-je vendre Granit moi-même ?",
        a: "Non. Vous faites la mise en relation, Granit s'occupe de la démo, de la signature et du démarrage.",
      },
      {
        q: "Comment mes recommandations sont-elles suivies ?",
        a: "Chaque établissement que vous nous présentez est rattaché à votre nom dans notre suivi. Vous savez où il en est, et la commission est due dès qu'il démarre.",
      },
    ],
  },
  en: {
    eyebrow: "Partner programme",
    titleLead: "Recommend Granit.",
    titleAccent: "Get paid for every client that signs.",
    intro:
      "You work with healthcare professionals: dental practices, opticians, hearing care, pharmacies, clinics, care homes, labs. Introduce them to Granit, we handle the demo and onboarding, you earn a commission.",
    cta: "Become a partner",
    flow: [
      { k: "You", v: "introduce Granit to a healthcare professional" },
      { k: "Granit", v: "runs the demo and follow-up" },
      { k: "The practice", v: "goes live, nothing to install" },
      { k: "You", v: "get paid" },
    ],
    whyEyebrow: "Benefits",
    whyTitle: "A simple programme,",
    whyAccent: "built for the field.",
    why: [
      {
        title: "A pain your clients feel every day",
        text: "Third-party billing, rejections, invoicing, follow-ups, admin files: paperwork weighs on every healthcare business. Granit agents take it over, on top of their existing tools.",
      },
      {
        title: "A commission on every signed client",
        text: "A bonus per practice or a recurring percentage: we pick the formula that fits your business together, in writing, before your first referral.",
      },
      {
        title: "You refer, we do the rest",
        text: "No selling required. You get a presentation kit and a dedicated contact at Granit who runs the demo, the onboarding and keeps you posted.",
      },
    ],
    sectorsEyebrow: "Where our agents run",
    sectors: ["Dental", "Optical", "Hearing care", "Clinic", "Care homes", "Pharmacy", "Pharma lab", "Bio lab", "Orthodontics"],
    sectorsLink: "See the agents",
    whoEyebrow: "Who it's for",
    who: [
      "Third-party billing managers",
      "Healthcare consultants and trainers",
      "Accountants",
      "Groups, networks and federations",
      "Software vendors and suppliers",
      "Healthcare content creators",
    ],
    stepsEyebrow: "How it works",
    stepsTitle: "Three steps,",
    stepsAccent: "no paperwork.",
    steps: [
      { n: "01", title: "Apply", text: "Two minutes, with the form below." },
      {
        n: "02",
        title: "Let's talk",
        text: "Twenty minutes to meet, set your commission and send you the partner kit.",
      },
      {
        n: "03",
        title: "Refer",
        text: "Introduce a practice, we handle everything, and you get paid when they go live.",
      },
    ],
    formEyebrow: "Application",
    formTitle: "Join the programme",
    formIntro: "We get back to you within 48h to set up a first call.",
    fields: {
      name: "Full name",
      email: "Email",
      phone: "Phone",
      company: "Company",
      profile: "Your business",
      message: "How would you recommend Granit? (optional)",
    },
    placeholders: {
      name: "Marie Dupont",
      email: "marie@consulting.fr",
      phone: "+33 6 12 34 56 78",
      company: "Firm, company, network…",
      message: "Sectors and number of clients, newsletter, training…",
    },
    choose: "Choose…",
    profiles: [
      "Third-party billing manager",
      "Consultant / trainer",
      "Accountant",
      "Group / network / federation",
      "Software vendor / supplier",
      "Content creator",
      "Other",
    ],
    submit: "Send my application",
    sending: "Sending…",
    note: "Free, no commitment. Your data stays with us.",
    success: "Application received, thank you.",
    successSub: "We get back to you within 48h to set up a first call.",
    error: "Something went wrong. Please retry, or email us at contact@getgranit.ai.",
    faqTitle: "FAQ",
    faq: [
      {
        q: "Do I need to be a Granit client to become a partner?",
        a: "No. The programme is open to anyone who works with healthcare professionals, whatever their job.",
      },
      {
        q: "How much will I earn?",
        a: "It depends on your business: a fixed bonus per signed practice, or a recurring percentage. We set it together on the first call, in writing.",
      },
      {
        q: "Do I have to sell Granit myself?",
        a: "No. You make the introduction, Granit handles the demo, signature and onboarding.",
      },
      {
        q: "How are my referrals tracked?",
        a: "Every practice you introduce is tied to your name in our pipeline. You know where they stand, and the commission is due once they go live.",
      },
    ],
  },
};

export type AffiliationCopy = (typeof copy)["fr"];
