/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AffiliationRouteImport } from './routes/affiliation'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CasUsageRouteImport } from './routes/cas-usage'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProduitRouteImport } from './routes/produit'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as SilmoRouteImport } from './routes/silmo'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as BlogSplatRouteImport } from './routes/blog.$'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnCgvRouteImport } from './routes/en.cgv'
import { Route as RessourcesIndexRouteImport } from './routes/ressources.index'
import { Route as RessourcesSlugRouteImport } from './routes/ressources.$slug'
import { Route as EnBlogSplatRouteImport } from './routes/en.blog.$'
import { Route as RessourcesCategorieCategoryRouteImport } from './routes/ressources.categorie.$category'
import { Route as RessourcesMetierVerticaleRouteImport } from './routes/ressources.metier.$verticale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliationRoute = AffiliationRouteImport.update({
  id: '/affiliation',
  path: '/affiliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CasUsageRoute = CasUsageRouteImport.update({
  id: '/cas-usage',
  path: '/cas-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitRoute = ProduitRouteImport.update({
  id: '/produit',
  path: '/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const SilmoRoute = SilmoRouteImport.update({
  id: '/silmo',
  path: '/silmo',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCgvRoute = EnCgvRouteImport.update({
  id: '/en/cgv',
  path: '/en/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesIndexRoute = RessourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesSlugRoute = RessourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RessourcesRoute,
} as any)
const EnBlogSplatRoute = EnBlogSplatRouteImport.update({
  id: '/en/blog/$',
  path: '/en/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesCategorieCategoryRoute =
  RessourcesCategorieCategoryRouteImport.update({
    id: '/categorie/$category',
    path: '/categorie/$category',
    getParentRoute: () => RessourcesRoute,
  } as any)
const RessourcesMetierVerticaleRoute =
  RessourcesMetierVerticaleRouteImport.update({
    id: '/metier/$verticale',
    path: '/metier/$verticale',
    getParentRoute: () => RessourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/affiliation': typeof AffiliationRoute
  '/agents': typeof AgentsRoute
  '/cas-usage': typeof CasUsageRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/produit': typeof ProduitRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/securite': typeof SecuriteRoute
  '/silmo': typeof SilmoRoute
  '/tarifs': typeof TarifsRoute
  '/blog/$': typeof BlogSplatRoute
  '/en/cgv': typeof EnCgvRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/en/': typeof EnIndexRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/en/blog/$': typeof EnBlogSplatRoute
  '/ressources/categorie/$category': typeof RessourcesCategorieCategoryRoute
  '/ressources/metier/$verticale': typeof RessourcesMetierVerticaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/affiliation': typeof AffiliationRoute
  '/agents': typeof AgentsRoute
  '/cas-usage': typeof CasUsageRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/produit': typeof ProduitRoute
  '/securite': typeof SecuriteRoute
  '/silmo': typeof SilmoRoute
  '/tarifs': typeof TarifsRoute
  '/blog/$': typeof BlogSplatRoute
  '/en/cgv': typeof EnCgvRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/en': typeof EnIndexRoute
  '/ressources': typeof RessourcesIndexRoute
  '/en/blog/$': typeof EnBlogSplatRoute
  '/ressources/categorie/$category': typeof RessourcesCategorieCategoryRoute
  '/ressources/metier/$verticale': typeof RessourcesMetierVerticaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/affiliation': typeof AffiliationRoute
  '/agents': typeof AgentsRoute
  '/cas-usage': typeof CasUsageRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/produit': typeof ProduitRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/securite': typeof SecuriteRoute
  '/silmo': typeof SilmoRoute
  '/tarifs': typeof TarifsRoute
  '/blog/$': typeof BlogSplatRoute
  '/en/cgv': typeof EnCgvRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/en/': typeof EnIndexRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/en/blog/$': typeof EnBlogSplatRoute
  '/ressources/categorie/$category': typeof RessourcesCategorieCategoryRoute
  '/ressources/metier/$verticale': typeof RessourcesMetierVerticaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/affiliation'
    | '/agents'
    | '/cas-usage'
    | '/cgv'
    | '/contact'
    | '/demo'
    | '/privacy'
    | '/produit'
    | '/ressources'
    | '/securite'
    | '/silmo'
    | '/tarifs'
    | '/blog/$'
    | '/en/cgv'
    | '/ressources/$slug'
    | '/en/'
    | '/ressources/'
    | '/en/blog/$'
    | '/ressources/categorie/$category'
    | '/ressources/metier/$verticale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/affiliation'
    | '/agents'
    | '/cas-usage'
    | '/cgv'
    | '/contact'
    | '/demo'
    | '/privacy'
    | '/produit'
    | '/securite'
    | '/silmo'
    | '/tarifs'
    | '/blog/$'
    | '/en/cgv'
    | '/ressources/$slug'
    | '/en'
    | '/ressources'
    | '/en/blog/$'
    | '/ressources/categorie/$category'
    | '/ressources/metier/$verticale'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/affiliation'
    | '/agents'
    | '/cas-usage'
    | '/cgv'
    | '/contact'
    | '/demo'
    | '/privacy'
    | '/produit'
    | '/ressources'
    | '/securite'
    | '/silmo'
    | '/tarifs'
    | '/blog/$'
    | '/en/cgv'
    | '/ressources/$slug'
    | '/en/'
    | '/ressources/'
    | '/en/blog/$'
    | '/ressources/categorie/$category'
    | '/ressources/metier/$verticale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AffiliationRoute: typeof AffiliationRoute
  AgentsRoute: typeof AgentsRoute
  CasUsageRoute: typeof CasUsageRoute
  CgvRoute: typeof CgvRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  PrivacyRoute: typeof PrivacyRoute
  ProduitRoute: typeof ProduitRoute
  RessourcesRoute: typeof RessourcesRouteWithChildren
  SecuriteRoute: typeof SecuriteRoute
  SilmoRoute: typeof SilmoRoute
  TarifsRoute: typeof TarifsRoute
  BlogSplatRoute: typeof BlogSplatRoute
  EnCgvRoute: typeof EnCgvRoute
  EnIndexRoute: typeof EnIndexRoute
  EnBlogSplatRoute: typeof EnBlogSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliation': {
      id: '/affiliation'
      path: '/affiliation'
      fullPath: '/affiliation'
      preLoaderRoute: typeof AffiliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-usage': {
      id: '/cas-usage'
      path: '/cas-usage'
      fullPath: '/cas-usage'
      preLoaderRoute: typeof CasUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit': {
      id: '/produit'
      path: '/produit'
      fullPath: '/produit'
      preLoaderRoute: typeof ProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silmo': {
      id: '/silmo'
      path: '/silmo'
      fullPath: '/silmo'
      preLoaderRoute: typeof SilmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/cgv': {
      id: '/en/cgv'
      path: '/en/cgv'
      fullPath: '/en/cgv'
      preLoaderRoute: typeof EnCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/': {
      id: '/ressources/'
      path: '/'
      fullPath: '/ressources/'
      preLoaderRoute: typeof RessourcesIndexRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/$slug': {
      id: '/ressources/$slug'
      path: '/$slug'
      fullPath: '/ressources/$slug'
      preLoaderRoute: typeof RessourcesSlugRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/en/blog/$': {
      id: '/en/blog/$'
      path: '/en/blog/$'
      fullPath: '/en/blog/$'
      preLoaderRoute: typeof EnBlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/categorie/$category': {
      id: '/ressources/categorie/$category'
      path: '/categorie/$category'
      fullPath: '/ressources/categorie/$category'
      preLoaderRoute: typeof RessourcesCategorieCategoryRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/metier/$verticale': {
      id: '/ressources/metier/$verticale'
      path: '/metier/$verticale'
      fullPath: '/ressources/metier/$verticale'
      preLoaderRoute: typeof RessourcesMetierVerticaleRouteImport
      parentRoute: typeof RessourcesRoute
    }
  }
}

interface RessourcesRouteChildren {
  RessourcesSlugRoute: typeof RessourcesSlugRoute
  RessourcesIndexRoute: typeof RessourcesIndexRoute
  RessourcesCategorieCategoryRoute: typeof RessourcesCategorieCategoryRoute
  RessourcesMetierVerticaleRoute: typeof RessourcesMetierVerticaleRoute
}

const RessourcesRouteChildren: RessourcesRouteChildren = {
  RessourcesSlugRoute: RessourcesSlugRoute,
  RessourcesIndexRoute: RessourcesIndexRoute,
  RessourcesCategorieCategoryRoute: RessourcesCategorieCategoryRoute,
  RessourcesMetierVerticaleRoute: RessourcesMetierVerticaleRoute,
}

const RessourcesRouteWithChildren = RessourcesRoute._addFileChildren(
  RessourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AffiliationRoute: AffiliationRoute,
  AgentsRoute: AgentsRoute,
  CasUsageRoute: CasUsageRoute,
  CgvRoute: CgvRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  PrivacyRoute: PrivacyRoute,
  ProduitRoute: ProduitRoute,
  RessourcesRoute: RessourcesRouteWithChildren,
  SecuriteRoute: SecuriteRoute,
  SilmoRoute: SilmoRoute,
  TarifsRoute: TarifsRoute,
  BlogSplatRoute: BlogSplatRoute,
  EnCgvRoute: EnCgvRoute,
  EnIndexRoute: EnIndexRoute,
  EnBlogSplatRoute: EnBlogSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
