/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as ProduitRouteImport } from './routes/produit'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CasUsageRouteImport } from './routes/cas-usage'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RessourcesIndexRouteImport } from './routes/ressources.index'
import { Route as RessourcesSlugRouteImport } from './routes/ressources.$slug'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitRoute = ProduitRouteImport.update({
  id: '/produit',
  path: '/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CasUsageRoute = CasUsageRouteImport.update({
  id: '/cas-usage',
  path: '/cas-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesIndexRoute = RessourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RessourcesRoute,
} as any)
const RessourcesSlugRoute = RessourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RessourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agents': typeof AgentsRoute
  '/cas-usage': typeof CasUsageRoute
  '/cgv': typeof CgvRoute
  '/demo': typeof DemoRoute
  '/produit': typeof ProduitRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/securite': typeof SecuriteRoute
  '/tarifs': typeof TarifsRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/ressources/': typeof RessourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agents': typeof AgentsRoute
  '/cas-usage': typeof CasUsageRoute
  '/cgv': typeof CgvRoute
  '/demo': typeof DemoRoute
  '/produit': typeof ProduitRoute
  '/securite': typeof SecuriteRoute
  '/tarifs': typeof TarifsRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/ressources': typeof RessourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agents': typeof AgentsRoute
  '/cas-usage': typeof CasUsageRoute
  '/cgv': typeof CgvRoute
  '/demo': typeof DemoRoute
  '/produit': typeof ProduitRoute
  '/ressources': typeof RessourcesRouteWithChildren
  '/securite': typeof SecuriteRoute
  '/tarifs': typeof TarifsRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/ressources/': typeof RessourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/agents'
    | '/cas-usage'
    | '/cgv'
    | '/demo'
    | '/produit'
    | '/ressources'
    | '/securite'
    | '/tarifs'
    | '/ressources/$slug'
    | '/ressources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/agents'
    | '/cas-usage'
    | '/cgv'
    | '/demo'
    | '/produit'
    | '/securite'
    | '/tarifs'
    | '/ressources/$slug'
    | '/ressources'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/agents'
    | '/cas-usage'
    | '/cgv'
    | '/demo'
    | '/produit'
    | '/ressources'
    | '/securite'
    | '/tarifs'
    | '/ressources/$slug'
    | '/ressources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AgentsRoute: typeof AgentsRoute
  CasUsageRoute: typeof CasUsageRoute
  CgvRoute: typeof CgvRoute
  DemoRoute: typeof DemoRoute
  ProduitRoute: typeof ProduitRoute
  RessourcesRoute: typeof RessourcesRouteWithChildren
  SecuriteRoute: typeof SecuriteRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit': {
      id: '/produit'
      path: '/produit'
      fullPath: '/produit'
      preLoaderRoute: typeof ProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-usage': {
      id: '/cas-usage'
      path: '/cas-usage'
      fullPath: '/cas-usage'
      preLoaderRoute: typeof CasUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/': {
      id: '/ressources/'
      path: '/'
      fullPath: '/ressources/'
      preLoaderRoute: typeof RessourcesIndexRouteImport
      parentRoute: typeof RessourcesRoute
    }
    '/ressources/$slug': {
      id: '/ressources/$slug'
      path: '/$slug'
      fullPath: '/ressources/$slug'
      preLoaderRoute: typeof RessourcesSlugRouteImport
      parentRoute: typeof RessourcesRoute
    }
  }
}

interface RessourcesRouteChildren {
  RessourcesSlugRoute: typeof RessourcesSlugRoute
  RessourcesIndexRoute: typeof RessourcesIndexRoute
}

const RessourcesRouteChildren: RessourcesRouteChildren = {
  RessourcesSlugRoute: RessourcesSlugRoute,
  RessourcesIndexRoute: RessourcesIndexRoute,
}

const RessourcesRouteWithChildren = RessourcesRoute._addFileChildren(
  RessourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AgentsRoute: AgentsRoute,
  CasUsageRoute: CasUsageRoute,
  CgvRoute: CgvRoute,
  DemoRoute: DemoRoute,
  ProduitRoute: ProduitRoute,
  RessourcesRoute: RessourcesRouteWithChildren,
  SecuriteRoute: SecuriteRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
